name: Cypress E2E (Parallel)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cypress:
    name: Run Cypress - ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Automacao-1
            spec: cypress/e2e/automationExercice/Regression_Excecice.feature
          - name: Automacao-2
            spec: cypress/e2e/automationExercice/Outro.feature
          - name: Automacao-3
            spec: cypress/e2e/automationExercice/Outro2.feature
          - name: Automacao-4
            spec: cypress/e2e/automationExercice/Outro3.feature
          - name: Automacao-5
            spec: cypress/e2e/automationExercice/Outro4.feature

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress
        run: npx cypress run --spec "${{ matrix.spec }}"

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-${{ matrix.name }}
          path: |
            cypress/videos/**
            cypress/screenshots/**
          if-no-files-found: ignore
